logging:
  level:
    org:
      springframework: debug
      springframework.security.web.FilterChainProxy: debug
      springframework.web: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: b348c72d10416e90b346
            clientSecret: 912cb93d0a7a00af77abe1fe3972a6da0eb9a5e7
