logging:
  level:
    org:
      springframework: debug
      springframework.security.web.FilterChainProxy: debug
      springframework.web: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
    jpa:
      show-sql: true

jwt:
  expire:
    timeout:
      ms: 30000000
  signing:
    key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ